# 4.1 WarmingUpExercise: Basic Vector and Matrix Operation with Numpy.

##Problem- 1: Array Creation:



In [2]:

import numpy as np
import time


1. Initialize an empty array with size 2X2.

In [3]:
# empty 2x2
empty_2x2 = np.empty((2,2))
print("empty_2x2:\n", empty_2x2)


empty_2x2:
 [[9.41260094e-316 0.00000000e+000]
 [4.94065646e-324 6.87433983e-310]]


2. Initialize an all one array with size 4X2.

In [4]:
# ones 4x2
ones_4x2 = np.ones((4,2), dtype=int)
print("ones_4x2:\n", ones_4x2)


ones_4x2:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]]


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [5]:
# full
filled_3x3 = np.full((3,3), fill_value=7)  # example fill_value=7
print("filled_3x3:\n", filled_3x3)

filled_3x3:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [6]:
#  zeros_like
sample = np.array([[1,2,3],[4,5,6]])
zeros_like_sample = np.zeros_like(sample)
print("sample:\n", sample)
print("zeros_like_sample:\n", zeros_like_sample)


sample:
 [[1 2 3]
 [4 5 6]]
zeros_like_sample:
 [[0 0 0]
 [0 0 0]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [7]:
# ones_like
ones_like_sample = np.ones_like(sample)
print("ones_like_sample:\n", ones_like_sample)


ones_like_sample:
 [[1 1 1]
 [1 1 1]]


 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [8]:
# list - array
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print("arr_from_list:", arr_from_list)


arr_from_list: [1 2 3 4]


# Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [9]:

arr_10_49 = np.arange(10, 50)
print("arr_10_49:\n", arr_10_49)


arr_10_49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [10]:

mat_3x3 = np.arange(9).reshape((3,3))
print("mat_3x3:\n", mat_3x3)


mat_3x3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


 3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [11]:

eye_3x3 = np.eye(3, dtype=int)
print("eye_3x3:\n", eye_3x3)


eye_3x3:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [12]:

rand30 = np.random.random(30)
mean_rand30 = rand30.mean()
print("rand30:\n", rand30)
print("mean(rand30):", mean_rand30)


rand30:
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
mean(rand30): 0.43859727209743676


 5. Create a 10X10 array with random values and find the minimum and maximum values

In [13]:

rand10x10 = np.random.random((10,10))
min_val = rand10x10.min()
max_val = rand10x10.max()
print("rand10x10:\n", rand10x10)
print("min:", min_val, "max:", max_val)


rand10x10:
 [[0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.32518332
  0.72960618 0.63755747 0.88721274 0.47221493]
 [0.11959425 0.71324479 0.76078505 0.5612772  0.77096718 0.4937956
  0.52273283 0.42754102 0.02541913 0.10789143]
 [0.03142919 0.63641041 0.31435598 0.50857069 0.90756647 0.24929223
  0.41038292 0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765 0.80812038 0.63340376 0.87146059
 

6. Create a zero array of size 10 and replace 5th element with 1.

In [14]:

zero10 = np.zeros(10, dtype=int)
zero10[4] = 1
print("zero10:", zero10)


zero10: [0 0 0 0 1 0 0 0 0 0]


 7. Reverse an array arr = [1,2,0,0,4,0].

In [15]:

arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("original:", arr)
print("reversed:", reversed_arr)


original: [1 2 0 0 4 0]
reversed: [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [16]:

def border_ones(n):
    a = np.zeros((n,n), dtype=int)
    a[0,:] = 1
    a[-1,:] = 1
    a[:,0] = 1
    a[:,-1] = 1
    return a

border_5 = border_ones(5)
print("5x5 border ones:\n", border_5)


5x5 border ones:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [17]:

checker = np.indices((8,8)).sum(axis=0) % 2
print("8x8 checkerboard pattern:\n", checker)


8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem- 3: Array Operations:

In [18]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])


1. Add the two array.

In [19]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
add_xy = x + y
print("x + y:\n", add_xy)


x + y:
 [[ 6  8]
 [10 13]]


 2. Subtract the two array.

In [20]:

sub_xy = x - y
print("x - y:\n", sub_xy)


x - y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [21]:

mul_x = x * 3
print("x * 3:\n", mul_x)


x * 3:
 [[ 3  6]
 [ 9 15]]


 4. Find the square of each element of the array.

In [22]:
sq_x = x**2
print("x squared:\n", sq_x)


x squared:
 [[ 1  4]
 [ 9 25]]


 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [23]:

v = np.array([9,10])
w = np.array([11,12])

dot_vw = np.dot(v, w)        # scalar
x_dot_v = x.dot(v)           # array (matrix-vector)
x_dot_y = x.dot(y)           # matrix-matrix

print("v·w:", dot_vw)
print("x·v:", x_dot_v)
print("x·y:\n", x_dot_y)


v·w: 219
x·v: [29 77]
x·y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.

In [24]:

concat_xy_axis0 = np.concatenate((x, y), axis=0)  # vertical stack
concat_vw_col = np.column_stack((v, w))           # columns = v, w

print("concat x,y along rows (axis=0):\n", concat_xy_axis0)
print("concat v,w as columns:\n", concat_vw_col)


concat x,y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
concat v,w as columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [25]:

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("concat x and v result:\n", concat_xv)
except Exception as e:
    print("Concatenation error (expected):", e)
    print("\nExplanation: x has shape", x.shape, "while v has shape", v.shape,
          ". You cannot concatenate along axis=0 because row widths (number of columns) differ.")


Concatenation error (expected): all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: x has shape (2, 2) while v has shape (2,) . You cannot concatenate along axis=0 because row widths (number of columns) differ.


#Problem- 4: Matrix Operations:

In [26]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


 1. Prove A.A−1 = I.

In [27]:

A = np.array([[3,4],[7,8]], dtype=float)
A_inv = np.linalg.inv(A)
product_A_Ainv = A.dot(A_inv)
print("A @ A_inv:\n", product_A_Ainv)
print("Is close to identity? ->", np.allclose(product_A_Ainv, np.eye(2)))


A @ A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is close to identity? -> True


2. Prove AB̸ = BA.

In [28]:

B = np.array([[5,3],[2,1]], dtype=float)
AB = A.dot(B)
BA = B.dot(A)
print("A @ B:\n", AB)
print("B @ A:\n", BA)
print("Are AB and BA equal (elementwise)? ->", np.array_equal(AB, BA))


A @ B:
 [[23. 13.]
 [51. 29.]]
B @ A:
 [[36. 44.]
 [13. 16.]]
Are AB and BA equal (elementwise)? -> False


3. Prove (AB)T = BTAT.

In [29]:

lhs = (A.dot(B)).T
rhs = B.T.dot(A.T)
print("(A@B).T:\n", lhs)
print("B.T @ A.T:\n", rhs)
print("Are they equal (allclose)? ->", np.allclose(lhs, rhs))


(A@B).T:
 [[23. 51.]
 [13. 29.]]
B.T @ A.T:
 [[23. 51.]
 [13. 29.]]
Are they equal (allclose)? -> True


 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [34]:

# Solve linear system
M = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)
C = np.array([-1, -3, 9], dtype=float)

# Solve with np.linalg.solve (preferred)
sol_solve = np.linalg.solve(M, C)

# Solve using inverse (explicit) to compare
M_inv = np.linalg.inv(M)
sol_inv = M_inv.dot(C)

print("Solution using np.linalg.solve:", sol_solve)
print("Solution using inverse:", sol_inv)
print("Are solutions equal? ->", np.allclose(sol_solve, sol_inv))


Solution using np.linalg.solve: [ 2.  1. -2.]
Solution using inverse: [ 2.  1. -2.]
Are solutions equal? -> True


#4.2 Experiment: How Fast is Numpy?

In [35]:
# Experiment - timings for list vs numpy
import time

N = 1_000_000

# Prepare data
list_a = list(range(N))
list_b = list(range(N))
np_a = np.arange(N)
np_b = np.arange(N)

# 1. Element-wise addition
start = time.time()
list_add = [list_a[i] + list_b[i] for i in range(N)]
time_list_add = time.time() - start

start = time.time()
np_add = np_a + np_b
time_np_add = time.time() - start

# 2. Element-wise multiplication
start = time.time()
list_mul = [list_a[i] * list_b[i] for i in range(N)]
time_list_mul = time.time() - start

start = time.time()
np_mul = np_a * np_b
time_np_mul = time.time() - start

# 3. Dot product
start = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(N))
time_list_dot = time.time() - start

start = time.time()
np_dot = np.dot(np_a, np_b)
time_np_dot = time.time() - start

# 4. Matrix multiplication (NumPy only here for 1000x1000)
size = 1000
A = np.random.random((size, size))
B = np.random.random((size, size))
start = time.time()
np_matmul = A.dot(B)
time_np_matmul = time.time() - start

# Print timings
print("Timings (seconds):")
print(f"list add: {time_list_add:.4f} | numpy add: {time_np_add:.4f}")
print(f"list mul: {time_list_mul:.4f} | numpy mul: {time_np_mul:.4f}")
print(f"list dot: {time_list_dot:.4f} | numpy dot: {time_np_dot:.4f}")
print(f"numpy 1000x1000 matmul: {time_np_matmul:.4f}")


Timings (seconds):
list add: 0.1824 | numpy add: 0.0057
list mul: 0.1935 | numpy mul: 0.0063
list dot: 0.1993 | numpy dot: 0.0023
numpy 1000x1000 matmul: 0.1208
